package com.mtbs3d.minecrift.control;

public enum ViveButtons  {
 BUTTON_LEFT_TRIGGER ,
 BUTTON_LEFT_TRIGGER_FULLCLICK,
 BUTTON_LEFT_APPMENU,
 BUTTON_LEFT_TOUCHPAD_UL,
 BUTTON_LEFT_TOUCHPAD_UR,
 BUTTON_LEFT_TOUCHPAD_BL,
 BUTTON_LEFT_TOUCHPAD_BR,
 BUTTON_LEFT_GRIP,
 BUTTON_RIGHT_TRIGGER,
 BUTTON_RIGHT_TRIGGER_FULLCLICK,
 BUTTON_RIGHT_APPMENU,
 BUTTON_RIGHT_TOUCHPAD_UL,
 BUTTON_RIGHT_TOUCHPAD_UR,
 BUTTON_RIGHT_TOUCHPAD_BL,
 BUTTON_RIGHT_TOUCHPAD_BR,
 BUTTON_RIGHT_GRIP,
 OCULUS_LEFT_INDEX_TRIGGER_TOUCH,
 OCULUS_LEFT_INDEX_TRIGGER_PRESS,
 OCULUS_LEFT_HAND_TRIGGER_TOUCH,
 OCULUS_LEFT_HAND_TRIGGER_PRESS,
 OCULUS_LEFT_Y_PRESS,
 OCULUS_LEFT_Y_TOUCH,
 OCULUS_LEFT_STICK_PRESS,
 OCULUS_LEFT_STICK_TOUCH,
 OCULUS_LEFT_X_PRESS,
 OCULUS_LEFT_X_TOUCH,
 OCULUS_RIGHT_INDEX_TRIGGER_TOUCH,
 OCULUS_RIGHT_INDEX_TRIGGER_PRESS,
 OCULUS_RIGHT_HAND_TRIGGER_TOUCH,
 OCULUS_RIGHT_HAND_TRIGGER_PRESS,
 OCULUS_RIGHT_B_PRESS,
 OCULUS_RIGHT_B_TOUCH,
 OCULUS_RIGHT_STICK_PRESS,
 OCULUS_RIGHT_STICK_TOUCH,
 OCULUS_RIGHT_A_PRESS,
 OCULUS_RIGHT_A_TOUCH
}



